// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: garyeong/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetAllReportsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetAllReportsRequest) Reset()         { *m = QueryGetAllReportsRequest{} }
func (m *QueryGetAllReportsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllReportsRequest) ProtoMessage()    {}
func (*QueryGetAllReportsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{2}
}
func (m *QueryGetAllReportsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllReportsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllReportsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllReportsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllReportsRequest.Merge(m, src)
}
func (m *QueryGetAllReportsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllReportsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllReportsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllReportsRequest proto.InternalMessageInfo

func (m *QueryGetAllReportsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetAllReportsResponse struct {
	Reports    []*Report           `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetAllReportsResponse) Reset()         { *m = QueryGetAllReportsResponse{} }
func (m *QueryGetAllReportsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetAllReportsResponse) ProtoMessage()    {}
func (*QueryGetAllReportsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{3}
}
func (m *QueryGetAllReportsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetAllReportsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetAllReportsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetAllReportsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetAllReportsResponse.Merge(m, src)
}
func (m *QueryGetAllReportsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetAllReportsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetAllReportsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetAllReportsResponse proto.InternalMessageInfo

func (m *QueryGetAllReportsResponse) GetReports() []*Report {
	if m != nil {
		return m.Reports
	}
	return nil
}

func (m *QueryGetAllReportsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetCommentsByReportIdRequest struct {
	ReportId   uint64             `protobuf:"varint,1,opt,name=reportId,proto3" json:"reportId,omitempty"`
	Pagination *query.PageRequest `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetCommentsByReportIdRequest) Reset()         { *m = QueryGetCommentsByReportIdRequest{} }
func (m *QueryGetCommentsByReportIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCommentsByReportIdRequest) ProtoMessage()    {}
func (*QueryGetCommentsByReportIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{4}
}
func (m *QueryGetCommentsByReportIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCommentsByReportIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCommentsByReportIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCommentsByReportIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCommentsByReportIdRequest.Merge(m, src)
}
func (m *QueryGetCommentsByReportIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCommentsByReportIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCommentsByReportIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCommentsByReportIdRequest proto.InternalMessageInfo

func (m *QueryGetCommentsByReportIdRequest) GetReportId() uint64 {
	if m != nil {
		return m.ReportId
	}
	return 0
}

func (m *QueryGetCommentsByReportIdRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetCommentsByReportIdResponse struct {
	Comments   []*Comment          `protobuf:"bytes,1,rep,name=comments,proto3" json:"comments,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryGetCommentsByReportIdResponse) Reset()         { *m = QueryGetCommentsByReportIdResponse{} }
func (m *QueryGetCommentsByReportIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCommentsByReportIdResponse) ProtoMessage()    {}
func (*QueryGetCommentsByReportIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{5}
}
func (m *QueryGetCommentsByReportIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCommentsByReportIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCommentsByReportIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCommentsByReportIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCommentsByReportIdResponse.Merge(m, src)
}
func (m *QueryGetCommentsByReportIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCommentsByReportIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCommentsByReportIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCommentsByReportIdResponse proto.InternalMessageInfo

func (m *QueryGetCommentsByReportIdResponse) GetComments() []*Comment {
	if m != nil {
		return m.Comments
	}
	return nil
}

func (m *QueryGetCommentsByReportIdResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetCommentByIdRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCommentByIdRequest) Reset()         { *m = QueryGetCommentByIdRequest{} }
func (m *QueryGetCommentByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCommentByIdRequest) ProtoMessage()    {}
func (*QueryGetCommentByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{6}
}
func (m *QueryGetCommentByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCommentByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCommentByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCommentByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCommentByIdRequest.Merge(m, src)
}
func (m *QueryGetCommentByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCommentByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCommentByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCommentByIdRequest proto.InternalMessageInfo

func (m *QueryGetCommentByIdRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCommentByIdResponse struct {
	Comment *Comment `protobuf:"bytes,1,opt,name=comment,proto3" json:"comment,omitempty"`
}

func (m *QueryGetCommentByIdResponse) Reset()         { *m = QueryGetCommentByIdResponse{} }
func (m *QueryGetCommentByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCommentByIdResponse) ProtoMessage()    {}
func (*QueryGetCommentByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{7}
}
func (m *QueryGetCommentByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCommentByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCommentByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCommentByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCommentByIdResponse.Merge(m, src)
}
func (m *QueryGetCommentByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCommentByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCommentByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCommentByIdResponse proto.InternalMessageInfo

func (m *QueryGetCommentByIdResponse) GetComment() *Comment {
	if m != nil {
		return m.Comment
	}
	return nil
}

type QueryGetReportsCountRequest struct {
}

func (m *QueryGetReportsCountRequest) Reset()         { *m = QueryGetReportsCountRequest{} }
func (m *QueryGetReportsCountRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetReportsCountRequest) ProtoMessage()    {}
func (*QueryGetReportsCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{8}
}
func (m *QueryGetReportsCountRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetReportsCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetReportsCountRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetReportsCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetReportsCountRequest.Merge(m, src)
}
func (m *QueryGetReportsCountRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetReportsCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetReportsCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetReportsCountRequest proto.InternalMessageInfo

type QueryGetReportsCountResponse struct {
	Count uint64 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
}

func (m *QueryGetReportsCountResponse) Reset()         { *m = QueryGetReportsCountResponse{} }
func (m *QueryGetReportsCountResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetReportsCountResponse) ProtoMessage()    {}
func (*QueryGetReportsCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{9}
}
func (m *QueryGetReportsCountResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetReportsCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetReportsCountResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetReportsCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetReportsCountResponse.Merge(m, src)
}
func (m *QueryGetReportsCountResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetReportsCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetReportsCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetReportsCountResponse proto.InternalMessageInfo

func (m *QueryGetReportsCountResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type QueryGetReportByIdRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetReportByIdRequest) Reset()         { *m = QueryGetReportByIdRequest{} }
func (m *QueryGetReportByIdRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetReportByIdRequest) ProtoMessage()    {}
func (*QueryGetReportByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{10}
}
func (m *QueryGetReportByIdRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetReportByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetReportByIdRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetReportByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetReportByIdRequest.Merge(m, src)
}
func (m *QueryGetReportByIdRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetReportByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetReportByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetReportByIdRequest proto.InternalMessageInfo

func (m *QueryGetReportByIdRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetReportByIdResponse struct {
	Report *Report `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
}

func (m *QueryGetReportByIdResponse) Reset()         { *m = QueryGetReportByIdResponse{} }
func (m *QueryGetReportByIdResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetReportByIdResponse) ProtoMessage()    {}
func (*QueryGetReportByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{11}
}
func (m *QueryGetReportByIdResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetReportByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetReportByIdResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetReportByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetReportByIdResponse.Merge(m, src)
}
func (m *QueryGetReportByIdResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetReportByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetReportByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetReportByIdResponse proto.InternalMessageInfo

func (m *QueryGetReportByIdResponse) GetReport() *Report {
	if m != nil {
		return m.Report
	}
	return nil
}

type QueryGetReportByTargetRequest struct {
	Target string `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
}

func (m *QueryGetReportByTargetRequest) Reset()         { *m = QueryGetReportByTargetRequest{} }
func (m *QueryGetReportByTargetRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetReportByTargetRequest) ProtoMessage()    {}
func (*QueryGetReportByTargetRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{12}
}
func (m *QueryGetReportByTargetRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetReportByTargetRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetReportByTargetRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetReportByTargetRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetReportByTargetRequest.Merge(m, src)
}
func (m *QueryGetReportByTargetRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetReportByTargetRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetReportByTargetRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetReportByTargetRequest proto.InternalMessageInfo

func (m *QueryGetReportByTargetRequest) GetTarget() string {
	if m != nil {
		return m.Target
	}
	return ""
}

type QueryGetReportByTargetResponse struct {
	Report []*Report `protobuf:"bytes,1,rep,name=report,proto3" json:"report,omitempty"`
}

func (m *QueryGetReportByTargetResponse) Reset()         { *m = QueryGetReportByTargetResponse{} }
func (m *QueryGetReportByTargetResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetReportByTargetResponse) ProtoMessage()    {}
func (*QueryGetReportByTargetResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b6b0a1fbe2c4eb88, []int{13}
}
func (m *QueryGetReportByTargetResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetReportByTargetResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetReportByTargetResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetReportByTargetResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetReportByTargetResponse.Merge(m, src)
}
func (m *QueryGetReportByTargetResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetReportByTargetResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetReportByTargetResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetReportByTargetResponse proto.InternalMessageInfo

func (m *QueryGetReportByTargetResponse) GetReport() []*Report {
	if m != nil {
		return m.Report
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "garyeong.garyeong.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "garyeong.garyeong.QueryParamsResponse")
	proto.RegisterType((*QueryGetAllReportsRequest)(nil), "garyeong.garyeong.QueryGetAllReportsRequest")
	proto.RegisterType((*QueryGetAllReportsResponse)(nil), "garyeong.garyeong.QueryGetAllReportsResponse")
	proto.RegisterType((*QueryGetCommentsByReportIdRequest)(nil), "garyeong.garyeong.QueryGetCommentsByReportIdRequest")
	proto.RegisterType((*QueryGetCommentsByReportIdResponse)(nil), "garyeong.garyeong.QueryGetCommentsByReportIdResponse")
	proto.RegisterType((*QueryGetCommentByIdRequest)(nil), "garyeong.garyeong.QueryGetCommentByIdRequest")
	proto.RegisterType((*QueryGetCommentByIdResponse)(nil), "garyeong.garyeong.QueryGetCommentByIdResponse")
	proto.RegisterType((*QueryGetReportsCountRequest)(nil), "garyeong.garyeong.QueryGetReportsCountRequest")
	proto.RegisterType((*QueryGetReportsCountResponse)(nil), "garyeong.garyeong.QueryGetReportsCountResponse")
	proto.RegisterType((*QueryGetReportByIdRequest)(nil), "garyeong.garyeong.QueryGetReportByIdRequest")
	proto.RegisterType((*QueryGetReportByIdResponse)(nil), "garyeong.garyeong.QueryGetReportByIdResponse")
	proto.RegisterType((*QueryGetReportByTargetRequest)(nil), "garyeong.garyeong.QueryGetReportByTargetRequest")
	proto.RegisterType((*QueryGetReportByTargetResponse)(nil), "garyeong.garyeong.QueryGetReportByTargetResponse")
}

func init() { proto.RegisterFile("garyeong/query.proto", fileDescriptor_b6b0a1fbe2c4eb88) }

var fileDescriptor_b6b0a1fbe2c4eb88 = []byte{
	// 783 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x96, 0x4d, 0x4f, 0x13, 0x5d,
	0x14, 0xc7, 0x7b, 0x0b, 0x14, 0x38, 0x4f, 0x1e, 0x9e, 0x70, 0x9f, 0x62, 0xe8, 0x00, 0x15, 0x26,
	0x88, 0xc8, 0xcb, 0x0c, 0x05, 0x14, 0x5d, 0x19, 0x4b, 0x22, 0x71, 0xa3, 0x38, 0xb8, 0x72, 0xd3,
	0x4c, 0xdb, 0x9b, 0x49, 0x93, 0x76, 0xee, 0x30, 0x33, 0x18, 0x2b, 0x61, 0x63, 0x4c, 0xdc, 0x9a,
	0xb8, 0x31, 0x2e, 0x8c, 0x31, 0xf1, 0x0b, 0xf8, 0x1d, 0x4c, 0x58, 0x92, 0xb8, 0x71, 0x65, 0x0c,
	0xf8, 0x41, 0x4c, 0xef, 0x3d, 0xd3, 0xe9, 0xcb, 0x74, 0x5a, 0x8c, 0x2b, 0x66, 0xce, 0x9c, 0x97,
	0xdf, 0x39, 0x9c, 0xf3, 0x4f, 0x21, 0x6d, 0x99, 0x6e, 0x9d, 0x71, 0xdb, 0xd2, 0x0f, 0x8f, 0x98,
	0x5b, 0xd7, 0x1c, 0x97, 0xfb, 0x9c, 0x4e, 0x06, 0x56, 0x2d, 0x78, 0x50, 0xd2, 0x16, 0xb7, 0xb8,
	0xf8, 0xaa, 0x37, 0x9e, 0xa4, 0xa3, 0x32, 0x6b, 0x71, 0x6e, 0x55, 0x99, 0x6e, 0x3a, 0x15, 0xdd,
	0xb4, 0x6d, 0xee, 0x9b, 0x7e, 0x85, 0xdb, 0x1e, 0x7e, 0x5d, 0x29, 0x71, 0xaf, 0xc6, 0x3d, 0xbd,
	0x68, 0x7a, 0x4c, 0xe6, 0xd7, 0x9f, 0xe5, 0x8a, 0xcc, 0x37, 0x73, 0xba, 0x63, 0x5a, 0x15, 0x5b,
	0x38, 0xa3, 0xef, 0x54, 0x13, 0xc4, 0x31, 0x5d, 0xb3, 0xe6, 0x75, 0x99, 0x6b, 0xbc, 0xcc, 0xaa,
	0x68, 0x56, 0xd3, 0x40, 0x1f, 0x37, 0xf2, 0xed, 0x0b, 0x5f, 0x83, 0x1d, 0x1e, 0x31, 0xcf, 0x57,
	0x1f, 0xc2, 0xff, 0x6d, 0x56, 0xcf, 0xe1, 0xb6, 0xc7, 0xe8, 0x0e, 0xa4, 0x64, 0xce, 0x69, 0x32,
	0x4f, 0x96, 0xff, 0xd9, 0xcc, 0x68, 0x5d, 0xed, 0x69, 0x32, 0x24, 0x3f, 0x7c, 0xfa, 0xe3, 0x6a,
	0xc2, 0x40, 0x77, 0xb5, 0x04, 0x19, 0x91, 0x6f, 0x8f, 0xf9, 0xf7, 0xaa, 0x55, 0x83, 0x39, 0xdc,
	0xf5, 0x83, 0x62, 0xf4, 0x3e, 0x40, 0xd8, 0x04, 0x66, 0x5e, 0xd2, 0x64, 0xc7, 0x5a, 0xa3, 0x63,
	0x4d, 0x4e, 0x14, 0x3b, 0xd6, 0xf6, 0x4d, 0x8b, 0x61, 0xac, 0xd1, 0x12, 0xa9, 0xbe, 0x27, 0xa0,
	0x44, 0x55, 0x41, 0xf8, 0x2d, 0x18, 0x75, 0xa5, 0x69, 0x9a, 0xcc, 0x0f, 0xf5, 0xa0, 0x97, 0x41,
	0x46, 0xe0, 0x49, 0xf7, 0xda, 0xd8, 0x92, 0x82, 0xed, 0x7a, 0x5f, 0x36, 0x59, 0xb1, 0x0d, 0xee,
	0x35, 0x81, 0x85, 0x00, 0x6e, 0x97, 0xd7, 0x6a, 0xcc, 0xf6, 0xbd, 0x7c, 0x5d, 0x96, 0x7b, 0x50,
	0x0e, 0x46, 0xa1, 0xc0, 0x98, 0x8b, 0x26, 0x31, 0x88, 0x61, 0xa3, 0xf9, 0xde, 0x31, 0xa6, 0xe4,
	0x1f, 0x8f, 0xe9, 0x33, 0x01, 0x35, 0x8e, 0x04, 0xc7, 0x75, 0x0b, 0xc6, 0x4a, 0xf8, 0x15, 0xe7,
	0xa5, 0x44, 0xcc, 0x0b, 0x13, 0x18, 0x4d, 0xdf, 0xbf, 0x37, 0xb1, 0xb5, 0xf0, 0xbf, 0x89, 0x55,
	0xf2, 0xf5, 0x70, 0x52, 0x13, 0x90, 0xac, 0x04, 0x33, 0x4a, 0x56, 0xca, 0xea, 0x01, 0xcc, 0x44,
	0x7a, 0x63, 0x37, 0xdb, 0x30, 0x8a, 0x84, 0xb8, 0x60, 0x71, 0xcd, 0x04, 0xae, 0xea, 0x5c, 0x98,
	0x14, 0xb7, 0x69, 0x97, 0x1f, 0xd9, 0x7e, 0x70, 0x25, 0xdb, 0x30, 0x1b, 0xfd, 0x19, 0x8b, 0xa6,
	0x61, 0xa4, 0xd4, 0x30, 0x20, 0xa6, 0x7c, 0x51, 0x57, 0xc3, 0x5b, 0x90, 0x51, 0x71, 0x6d, 0x3d,
	0x0a, 0x87, 0xd0, 0xea, 0x8c, 0x05, 0x72, 0x90, 0x92, 0xeb, 0x11, 0x73, 0x8f, 0xb8, 0xd1, 0xe8,
	0xa8, 0xee, 0xc0, 0x5c, 0x67, 0xc2, 0x27, 0xa6, 0x6b, 0xb1, 0xa0, 0x29, 0x7a, 0x05, 0x52, 0xbe,
	0x30, 0x88, 0x9c, 0xe3, 0x06, 0xbe, 0xa9, 0x07, 0x90, 0xed, 0x15, 0x18, 0x41, 0x33, 0x34, 0x10,
	0xcd, 0xe6, 0xab, 0x71, 0x18, 0x11, 0x59, 0xe9, 0x0b, 0x48, 0x49, 0xe5, 0xa0, 0xd7, 0x22, 0xc2,
	0xba, 0x25, 0x4a, 0x59, 0xea, 0xe7, 0x26, 0xa9, 0xd4, 0x85, 0x97, 0xdf, 0x7e, 0xbd, 0x4d, 0xce,
	0xd0, 0x8c, 0xde, 0x14, 0xc0, 0x0e, 0x81, 0xa4, 0xef, 0x08, 0xfc, 0xdb, 0xa6, 0x19, 0x74, 0xad,
	0x57, 0xf2, 0x28, 0x01, 0x53, 0xd6, 0x07, 0xf4, 0x46, 0xa2, 0x15, 0x41, 0xb4, 0x48, 0xd5, 0x08,
	0x22, 0x8b, 0xf9, 0x05, 0xb3, 0x5a, 0x2d, 0x04, 0xfa, 0xf3, 0x95, 0xc0, 0x54, 0xe4, 0x9d, 0xd2,
	0xed, 0x98, 0xa2, 0x3d, 0x05, 0x46, 0xb9, 0x79, 0xc9, 0x28, 0x44, 0xbe, 0x2b, 0x90, 0xef, 0xd0,
	0x9d, 0x1e, 0xc8, 0xc1, 0xf5, 0x17, 0x8a, 0x75, 0x44, 0x2f, 0x54, 0xca, 0xfa, 0x71, 0xa0, 0x5d,
	0x27, 0xf4, 0x13, 0x81, 0x89, 0xf6, 0xd3, 0xa4, 0xeb, 0xfd, 0x51, 0x5a, 0x2e, 0x43, 0xd1, 0x06,
	0x75, 0x47, 0xe4, 0x9c, 0x40, 0x5e, 0xa5, 0x37, 0xe2, 0x91, 0x1b, 0xc4, 0x0d, 0xd4, 0x4a, 0xf9,
	0x84, 0x7e, 0x24, 0xf0, 0x5f, 0xc7, 0x2d, 0xd3, 0xb8, 0xb2, 0x11, 0x9a, 0xa0, 0xe8, 0x03, 0xfb,
	0x23, 0xe7, 0x9a, 0xe0, 0x5c, 0xa2, 0x8b, 0x3d, 0x38, 0x71, 0x13, 0x0a, 0x42, 0x3c, 0xe8, 0x07,
	0xb9, 0xaa, 0xa1, 0x16, 0xc4, 0xae, 0x6a, 0x97, 0xbe, 0xc4, 0xae, 0x6a, 0xb7, 0xc0, 0xa8, 0x1b,
	0x02, 0x6e, 0x85, 0x2e, 0xc7, 0xc2, 0xb5, 0xce, 0xf0, 0x0b, 0x81, 0xc9, 0x2e, 0x89, 0xa0, 0x1b,
	0x03, 0x94, 0x6d, 0x93, 0x21, 0x25, 0x77, 0x89, 0x08, 0x84, 0xbd, 0x2d, 0x60, 0x37, 0xe9, 0x46,
	0x5f, 0x58, 0x29, 0x69, 0xfa, 0xb1, 0xfc, 0x7b, 0x92, 0xdf, 0x3a, 0x3d, 0xcf, 0x92, 0xb3, 0xf3,
	0x2c, 0xf9, 0x79, 0x9e, 0x25, 0x6f, 0x2e, 0xb2, 0x89, 0xb3, 0x8b, 0x6c, 0xe2, 0xfb, 0x45, 0x36,
	0xf1, 0x34, 0xd3, 0xcc, 0xf0, 0x3c, 0x4c, 0xe6, 0xd7, 0x1d, 0xe6, 0x15, 0x53, 0xe2, 0x07, 0xd4,
	0xd6, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2d, 0xdd, 0x6d, 0x1d, 0xf9, 0x09, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a list of GetAllReports items.
	GetAllReports(ctx context.Context, in *QueryGetAllReportsRequest, opts ...grpc.CallOption) (*QueryGetAllReportsResponse, error)
	// Queries a list of GetCommentsByReportId items.
	GetCommentsByReportId(ctx context.Context, in *QueryGetCommentsByReportIdRequest, opts ...grpc.CallOption) (*QueryGetCommentsByReportIdResponse, error)
	// Queries a list of GetCommentById items.
	GetCommentById(ctx context.Context, in *QueryGetCommentByIdRequest, opts ...grpc.CallOption) (*QueryGetCommentByIdResponse, error)
	// Queries a list of GetReportsCount items.
	GetReportsCount(ctx context.Context, in *QueryGetReportsCountRequest, opts ...grpc.CallOption) (*QueryGetReportsCountResponse, error)
	// Queries a list of GetReportById items.
	GetReportById(ctx context.Context, in *QueryGetReportByIdRequest, opts ...grpc.CallOption) (*QueryGetReportByIdResponse, error)
	// Queries a list of GetReportByTarget items.
	GetReportByTarget(ctx context.Context, in *QueryGetReportByTargetRequest, opts ...grpc.CallOption) (*QueryGetReportByTargetResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/garyeong.garyeong.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAllReports(ctx context.Context, in *QueryGetAllReportsRequest, opts ...grpc.CallOption) (*QueryGetAllReportsResponse, error) {
	out := new(QueryGetAllReportsResponse)
	err := c.cc.Invoke(ctx, "/garyeong.garyeong.Query/GetAllReports", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCommentsByReportId(ctx context.Context, in *QueryGetCommentsByReportIdRequest, opts ...grpc.CallOption) (*QueryGetCommentsByReportIdResponse, error) {
	out := new(QueryGetCommentsByReportIdResponse)
	err := c.cc.Invoke(ctx, "/garyeong.garyeong.Query/GetCommentsByReportId", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetCommentById(ctx context.Context, in *QueryGetCommentByIdRequest, opts ...grpc.CallOption) (*QueryGetCommentByIdResponse, error) {
	out := new(QueryGetCommentByIdResponse)
	err := c.cc.Invoke(ctx, "/garyeong.garyeong.Query/GetCommentById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetReportsCount(ctx context.Context, in *QueryGetReportsCountRequest, opts ...grpc.CallOption) (*QueryGetReportsCountResponse, error) {
	out := new(QueryGetReportsCountResponse)
	err := c.cc.Invoke(ctx, "/garyeong.garyeong.Query/GetReportsCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetReportById(ctx context.Context, in *QueryGetReportByIdRequest, opts ...grpc.CallOption) (*QueryGetReportByIdResponse, error) {
	out := new(QueryGetReportByIdResponse)
	err := c.cc.Invoke(ctx, "/garyeong.garyeong.Query/GetReportById", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetReportByTarget(ctx context.Context, in *QueryGetReportByTargetRequest, opts ...grpc.CallOption) (*QueryGetReportByTargetResponse, error) {
	out := new(QueryGetReportByTargetResponse)
	err := c.cc.Invoke(ctx, "/garyeong.garyeong.Query/GetReportByTarget", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a list of GetAllReports items.
	GetAllReports(context.Context, *QueryGetAllReportsRequest) (*QueryGetAllReportsResponse, error)
	// Queries a list of GetCommentsByReportId items.
	GetCommentsByReportId(context.Context, *QueryGetCommentsByReportIdRequest) (*QueryGetCommentsByReportIdResponse, error)
	// Queries a list of GetCommentById items.
	GetCommentById(context.Context, *QueryGetCommentByIdRequest) (*QueryGetCommentByIdResponse, error)
	// Queries a list of GetReportsCount items.
	GetReportsCount(context.Context, *QueryGetReportsCountRequest) (*QueryGetReportsCountResponse, error)
	// Queries a list of GetReportById items.
	GetReportById(context.Context, *QueryGetReportByIdRequest) (*QueryGetReportByIdResponse, error)
	// Queries a list of GetReportByTarget items.
	GetReportByTarget(context.Context, *QueryGetReportByTargetRequest) (*QueryGetReportByTargetResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetAllReports(ctx context.Context, req *QueryGetAllReportsRequest) (*QueryGetAllReportsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllReports not implemented")
}
func (*UnimplementedQueryServer) GetCommentsByReportId(ctx context.Context, req *QueryGetCommentsByReportIdRequest) (*QueryGetCommentsByReportIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentsByReportId not implemented")
}
func (*UnimplementedQueryServer) GetCommentById(ctx context.Context, req *QueryGetCommentByIdRequest) (*QueryGetCommentByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCommentById not implemented")
}
func (*UnimplementedQueryServer) GetReportsCount(ctx context.Context, req *QueryGetReportsCountRequest) (*QueryGetReportsCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportsCount not implemented")
}
func (*UnimplementedQueryServer) GetReportById(ctx context.Context, req *QueryGetReportByIdRequest) (*QueryGetReportByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportById not implemented")
}
func (*UnimplementedQueryServer) GetReportByTarget(ctx context.Context, req *QueryGetReportByTargetRequest) (*QueryGetReportByTargetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetReportByTarget not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/garyeong.garyeong.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAllReports_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetAllReportsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAllReports(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/garyeong.garyeong.Query/GetAllReports",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAllReports(ctx, req.(*QueryGetAllReportsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCommentsByReportId_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCommentsByReportIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCommentsByReportId(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/garyeong.garyeong.Query/GetCommentsByReportId",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCommentsByReportId(ctx, req.(*QueryGetCommentsByReportIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetCommentById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCommentByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetCommentById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/garyeong.garyeong.Query/GetCommentById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetCommentById(ctx, req.(*QueryGetCommentByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetReportsCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetReportsCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetReportsCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/garyeong.garyeong.Query/GetReportsCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetReportsCount(ctx, req.(*QueryGetReportsCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetReportById_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetReportByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetReportById(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/garyeong.garyeong.Query/GetReportById",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetReportById(ctx, req.(*QueryGetReportByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetReportByTarget_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetReportByTargetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetReportByTarget(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/garyeong.garyeong.Query/GetReportByTarget",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetReportByTarget(ctx, req.(*QueryGetReportByTargetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "garyeong.garyeong.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetAllReports",
			Handler:    _Query_GetAllReports_Handler,
		},
		{
			MethodName: "GetCommentsByReportId",
			Handler:    _Query_GetCommentsByReportId_Handler,
		},
		{
			MethodName: "GetCommentById",
			Handler:    _Query_GetCommentById_Handler,
		},
		{
			MethodName: "GetReportsCount",
			Handler:    _Query_GetReportsCount_Handler,
		},
		{
			MethodName: "GetReportById",
			Handler:    _Query_GetReportById_Handler,
		},
		{
			MethodName: "GetReportByTarget",
			Handler:    _Query_GetReportByTarget_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "garyeong/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetAllReportsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllReportsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllReportsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetAllReportsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetAllReportsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetAllReportsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Reports) > 0 {
		for iNdEx := len(m.Reports) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Reports[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCommentsByReportIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCommentsByReportIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCommentsByReportIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if m.ReportId != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.ReportId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCommentsByReportIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCommentsByReportIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCommentsByReportIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Comments) > 0 {
		for iNdEx := len(m.Comments) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Comments[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCommentByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCommentByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCommentByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCommentByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCommentByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCommentByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Comment != nil {
		{
			size, err := m.Comment.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetReportsCountRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetReportsCountRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetReportsCountRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryGetReportsCountResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetReportsCountResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetReportsCountResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Count != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Count))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetReportByIdRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetReportByIdRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetReportByIdRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetReportByIdResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetReportByIdResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetReportByIdResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Report != nil {
		{
			size, err := m.Report.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetReportByTargetRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetReportByTargetRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetReportByTargetRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Target) > 0 {
		i -= len(m.Target)
		copy(dAtA[i:], m.Target)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Target)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetReportByTargetResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetReportByTargetResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetReportByTargetResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Report) > 0 {
		for iNdEx := len(m.Report) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Report[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetAllReportsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetAllReportsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Reports) > 0 {
		for _, e := range m.Reports {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCommentsByReportIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReportId != 0 {
		n += 1 + sovQuery(uint64(m.ReportId))
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCommentsByReportIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Comments) > 0 {
		for _, e := range m.Comments {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetCommentByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCommentByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Comment != nil {
		l = m.Comment.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetReportsCountRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryGetReportsCountResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Count != 0 {
		n += 1 + sovQuery(uint64(m.Count))
	}
	return n
}

func (m *QueryGetReportByIdRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetReportByIdResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Report != nil {
		l = m.Report.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetReportByTargetRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Target)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetReportByTargetResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Report) > 0 {
		for _, e := range m.Report {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllReportsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllReportsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllReportsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetAllReportsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetAllReportsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetAllReportsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Reports", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Reports = append(m.Reports, &Report{})
			if err := m.Reports[len(m.Reports)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCommentsByReportIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCommentsByReportIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCommentsByReportIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReportId", wireType)
			}
			m.ReportId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReportId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCommentsByReportIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCommentsByReportIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCommentsByReportIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comments", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Comments = append(m.Comments, &Comment{})
			if err := m.Comments[len(m.Comments)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCommentByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCommentByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCommentByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCommentByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCommentByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCommentByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Comment", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Comment == nil {
				m.Comment = &Comment{}
			}
			if err := m.Comment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetReportsCountRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetReportsCountRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetReportsCountRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetReportsCountResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetReportsCountResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetReportsCountResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Count", wireType)
			}
			m.Count = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Count |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetReportByIdRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetReportByIdRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetReportByIdRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetReportByIdResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetReportByIdResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetReportByIdResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Report", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Report == nil {
				m.Report = &Report{}
			}
			if err := m.Report.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetReportByTargetRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetReportByTargetRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetReportByTargetRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Target", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Target = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetReportByTargetResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetReportByTargetResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetReportByTargetResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Report", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Report = append(m.Report, &Report{})
			if err := m.Report[len(m.Report)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
